### ISSUE TITLE
British English

### ISSUE THREAD

**Issue by TeaPermYouTube** [Aresiel/contact-me#1]
Hi, I speak (and write) in British English, and the Grammar Police bot keeps correcting my spelling, for example, when I type: "apologise", it notifies me saying it's spelled "apologized". Could you try adding British English too?
![Screenshot 2022-07-18 13 26 25](https://user-images.githubusercontent.com/109491383/179433527-9dc64587-717a-4676-9cf4-ea75dd1bc5b8.png)

**Comment by Aresiel** [comment]
Oh, what an oversight I've done. I thought I'd already configured it to use correct English..

**Comment by Aresiel** [comment]
I have switched the bot to british english, however, you might still get messages such as:
![image](https://user-images.githubusercontent.com/25839246/179434028-d666d94b-587b-47e7-bae6-0540b09ae87f.png)
I hope this is satisfactory.
